# Generated by Django 4.0.2 on 2022-02-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlecomment_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleComment',
            new_name='Comment',
        ),
    ]
