# Generated by Django 4.0.2 on 2022-02-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_articlecomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='article', verbose_name='Makaleye Fotoğraf Ekleyin'),
        ),
    ]
