# Generated by Django 4.0.2 on 2022-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='article', verbose_name='Makaleye Fotoğraf Ekleyin'),
        ),
    ]
